名称: 安卓CI

在:
  推动:
    分支: [ “主要” ]
  拉取请求:
    分支: [ “主要” ]

工作:
  建造:

    连续运行: ubuntu最新版本

    台阶:
    - 使用: 操作/签出@v4
    - 名称: 设置JDK 11
      使用: 操作/设置-java@v3
      与:
        java版本: '11'
        分布: 'temurin'
        缓存: Gradle

    - 名称: 授予gradlew的执行权限
      运行: chmod+x grated的
    - 名称: 使用Gradle构建
      运行: ./gradlew构建
